name: ci-nwearningscalculator-workflow
# on: [pull_request] # push, pull_request
on:
  pull_request:
    branches:
      - master
      
jobs:
  check-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.8.0'
      - run: npm install
      - run: npm run test